name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      ROLE_ARN: "arn:aws:iam::717240872783:role/GitHub-OIDC-role"
      AWS_DEFAULT_REGION: "ap-southeast-1"
    permissions:
      id-token: write   # This is required for requesting the JWT
    steps:

      # https://github.com/aws-actions/configure-aws-credentials
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: GitHub-Action-Role
          role-duration-seconds: 3600
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Check if AWS credentials are exported to env variables
        run: |
          env | grep AWS_
          aws sts get-caller-identity
          aws secretsmanager list-secrets
